# Generated by Django 4.0.3 on 2022-04-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cell',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
    ]
